// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfBRFVtGK1umH1DaWELmMN_paBUUQEy6Y',
    appId: '1:735054106972:web:9121c1579d6fba8d46b199',
    messagingSenderId: '735054106972',
    projectId: 'minimal-social-app-10cea',
    authDomain: 'minimal-social-app-10cea.firebaseapp.com',
    storageBucket: 'minimal-social-app-10cea.appspot.com',
    measurementId: 'G-Z7282RHWK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA84omY-4POwKsaMzVtp25VhgyM62LcZy0',
    appId: '1:735054106972:android:709d807ec646809246b199',
    messagingSenderId: '735054106972',
    projectId: 'minimal-social-app-10cea',
    storageBucket: 'minimal-social-app-10cea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu_TjgSVppSeujJ60oU3V0I5qfTtTvECw',
    appId: '1:735054106972:ios:05a31f5943c2893246b199',
    messagingSenderId: '735054106972',
    projectId: 'minimal-social-app-10cea',
    storageBucket: 'minimal-social-app-10cea.appspot.com',
    iosBundleId: 'com.example.minimalSosialMedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu_TjgSVppSeujJ60oU3V0I5qfTtTvECw',
    appId: '1:735054106972:ios:68d190781896e3f846b199',
    messagingSenderId: '735054106972',
    projectId: 'minimal-social-app-10cea',
    storageBucket: 'minimal-social-app-10cea.appspot.com',
    iosBundleId: 'com.example.minimalSosialMedia.RunnerTests',
  );
}
